# Generated by Django 4.2.20 on 2025-07-10 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='right',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
