# Generated by Django 4.2.20 on 2025-07-10 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_message_right'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='right',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='wrong',
            field=models.TextField(null=True),
        ),
    ]
