# Generated by Django 4.2.20 on 2025-07-10 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_alter_message_right_alter_message_wrong'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_user', models.CharField(max_length=255)),
                ('user_question', models.TextField(null=True)),
                ('question_answer', models.TextField(null=True)),
                ('user_choice', models.TextField(null=True)),
                ('question_detail', models.TextField(null=True)),
            ],
        ),
    ]
