# Generated by Django 4.2.20 on 2025-07-10 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='question_pk',
            field=models.BigIntegerField(null=True),
        ),
    ]
