# Generated by Django 4.2.20 on 2025-07-10 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0005_history_question_pk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='question_pk',
            field=models.TextField(null=True),
        ),
    ]
